// appSettings.js
// Key names must EXACTLY match the AS3 AppSettings constants (case-sensitive!)
module.exports = {
    // From AppSettings.as constant values:
    "ServerType":                           "unrestricted",
    "ShowCEOPLogo":                         "true",
    "ShowSIDLogo":                          "true",
    "showwebshoplink":                      "true",
    "PurchaseFlow":                         "1",
    "MalesMustWearTops":                    "false",
    "SnapshotServerUrl":                    "http://localhost:1600/",
    "SnapshotServiceHostName":              "localhost",
    "MaxConcurrentLoads":                   "5",
    "UserBehaviorServiceHostName":          "localhost",
    "UseUserBehaviorService":               "false",
    "UseUserNameFiltering":                 "false",
    "EcoSystemUrl":                         "http://localhost:1600/",
    "chatFMSServer":                        "rtmp://localhost/fms",
    "CommFMSServer":                        "rtmp://localhost/fms",
    "ImageUpload":                          "true",
    "worldpetmagazine":                     "true",
    "BlobServiceHostName":                  "localhost",
    "ChristmasStartDate":                   "12-01",
    "FMSAppName":                           "MSPWeb",

    // Exact keys from AS3 constants:
    "DeviceFingerprintCollectionEnabled":   "false",
    "specialinputtextchars":               "",
    "ModerationCheckUpdateTimerSeconds":    "60",
    "HelpCenterLink":                       "http://localhost:1600",
    "SafetyHelplineLink":                   "http://localhost:1600",
    "SafetyRulesLink":                      "http://localhost:1600",
    "portraitmode":                         "false",
    "UseOldMessagesList":                   "true",
    "MessageServiceELB":                    "http://localhost:1600",
    "MessageServerUrl":                     "http://localhost:1600",
    "SendMessagesToCassandraDatabase":      "false",
    "ReleaseVersion":                       "1.0",
    "clientidletimeout":                    "3600",
    "ActorDetailsCheckUpdateTimerSeconds":  "60",
    "SchoolFriendsSwitchEnabled":           "false",
    "XMPPFeatureState":                     "false",
    "AllowedNonFriendCommunication":        "true",
    "XmppUseLocalhost":                     "true",
    "XmppServerUrl":                        "localhost",
    "giftcertificateenabled":              "true",
    "MangroveAnalyticsFeatureUsageMinTime": "60",
    "LogMissingAssets":                     "true",
    "MySchoolFirstNameEnabled":             "false",
    "showoffercountdown":                   "false",
    "youtubeapikey":                        "",
    "EnableSpecialOffers":                  "false",
    "PhotoUploadOnWeb":                     "true",
    "clientExceptionReportCooldown":        "60",
    "enableClientExceptionLogging":         "false",
    "appsettingsversion":                   "1",
    "UserBehaviourFilterSymbol":            "",
};