// appSettings.js
console.log('✅ [appSettings] LOADED v2 (with Mangrove keys)'); 

module.exports = {
    "ServerType":                           "unrestricted",
    "ShowCEOPLogo":                         "true",
    "ShowSIDLogo":                          "true",
    "showwebshoplink":                      "true",
    "PurchaseFlow":                         "1",
    "MalesMustWearTops":                    "false",
    "SnapshotServerUrl":                    "http://localhost:1600/",
    "SnapshotServiceHostName":              "localhost",
    "MaxConcurrentLoads":                   "5",
    "UserBehaviorServiceHostName":          "localhost",
    "UseUserBehaviorService":               "false",
    "UseUserNameFiltering":                 "false",
    "EcoSystemUrl":                         "http://localhost:1600/",
    "chatFMSServer":                        "rtmp://localhost/fms",
    "CommFMSServer":                        "rtmp://localhost/fms",
    "ImageUpload":                          "true",
    "worldpetmagazine":                     "true",
    "BlobServiceHostName":                  "localhost",
    "ChristmasStartDate":                   "12-01",
    "FMSAppName":                           "MSPWeb",
    "DeviceFingerprintCollectionEnabled":   "false",
    "specialinputtextchars":                "",
    "ModerationCheckUpdateTimerSeconds":    "60",
    "HelpCenterLink":                       "http://localhost:1600",
    "SafetyHelplineLink":                   "http://localhost:1600",
    "SafetyRulesLink":                      "http://localhost:1600",
    "portraitmode":                         "false",
    "UseOldMessagesList":                   "true",
    "MessageServiceELB":                    "http://localhost:1600",
    "MessageServerUrl":                     "http://localhost:1600",
    "SendMessagesToCassandraDatabase":      "false",
    "ReleaseVersion":                       "1.0",
    "clientidletimeout":                    "3600",
    "ActorDetailsCheckUpdateTimerSeconds":  "60",
    "SchoolFriendsSwitchEnabled":           "false",
    "XMPPFeatureState":                     "false",
    "AllowedNonFriendCommunication":        "true",
    "XmppUseLocalhost":                     "true",
    "XmppServerUrl":                        "localhost",
    "giftcertificateenabled":               "true",
    "LogMissingAssets":                     "true",
    "MySchoolFirstNameEnabled":             "false",
    "showoffercountdown":                   "false",
    "youtubeapikey":                        "",
    "EnableSpecialOffers":                  "false",
    "PhotoUploadOnWeb":                     "true",
    "clientExceptionReportCooldown":        "60",
    "enableClientExceptionLogging":         "false",
    "appsettingsversion":                   "1",
    "UserBehaviourFilterSymbol":            "",

    // ⭐ THESE 6 KEYS ARE THE FIX FOR THE LOGIN CRASH ⭐
    "MangroveAnalyticsSwitch":              "false",
    "MangroveAnalyticsCollectorURL":        "http://localhost:1600/",
    "MangroveAnalyticsBufferSize":          "5",
    "MangroveAnalyticsDisabledEvents":      "",
    "MangroveAnalyticsDisableBase64":       "false",
    "MangroveAnalyticsFeatureUsageMinTime": "60",

    "ShopEnabled":                          "true",
    "MovieEnabled":                         "true",
    "ChatEnabled":                          "true",
    "ArtBookEnabled":                       "true",
    "CompetitionEnabled":                   "true",
    "AutogiftEnabled":                      "true",
    "GuestBookEnabled":                     "true",
    "MinUsernameLength":                    "3",
    "MaxUsernameLength":                    "40",
    "FamePointsPerLevel":                   "100",
    "MaxLevel":                             "101",
    "HighScoreListSize":                    "20",
    "NewsFeedEnabled":                      "true",
    "RoomEnabled":                          "true",
};