package com.moviestarplanet.core.controller.commands
{
   import com.moviestarplanet.Clubs.ClubRegistrator;
   import com.moviestarplanet.activityservice.valueObjects.Activity;
   import com.moviestarplanet.activityservice.valueObjects.ActivityActor;
   import com.moviestarplanet.activityservice.valueObjects.ActivityContest;
   import com.moviestarplanet.activityservice.valueObjects.ActivityDesign;
   import com.moviestarplanet.activityservice.valueObjects.ActivityExternalVideo;
   import com.moviestarplanet.activityservice.valueObjects.ActivityExternalVideoActorRel;
   import com.moviestarplanet.activityservice.valueObjects.ActivityExternalVideoPlaylistRel;
   import com.moviestarplanet.activityservice.valueObjects.ActivityImageUpload;
   import com.moviestarplanet.activityservice.valueObjects.ActivityLook;
   import com.moviestarplanet.activityservice.valueObjects.ActivityMood;
   import com.moviestarplanet.activityservice.valueObjects.ActivityMovie;
   import com.moviestarplanet.activityservice.valueObjects.ActivityScrapBlog;
   import com.moviestarplanet.activityservice.valueObjects.ActivityUpdater;
   import com.moviestarplanet.activityservice.valueObjects.ActivityWallPost;
   import com.moviestarplanet.activityservice.valueObjects.PagedActivityList;
   import com.moviestarplanet.activityservice.valueObjects.Todo;
   import com.moviestarplanet.activityservice.valueObjects.TodoActor;
   import com.moviestarplanet.activityservice.valueObjects.TodoContest;
   import com.moviestarplanet.activityservice.valueObjects.TodoMovie;
   import com.moviestarplanet.activityservice.valueObjects.TodoMovieCompetition;
   import com.moviestarplanet.activityservice.valueObjects.WallPostLink;
   import com.moviestarplanet.actorservice.valueObjects.AutographResponseVO;
   import com.moviestarplanet.admin.AdminRegistrator;
   import com.moviestarplanet.amf.PagerResultObject;
   import com.moviestarplanet.amf.valueobjects.AmfServiceResultData;
   import com.moviestarplanet.amf.valueobjects.ServiceResultData;
   import com.moviestarplanet.amf.valueobjects.TicketHeader;
   import com.moviestarplanet.anchorCharacters.SpecialCharactersRegistrator;
   import com.moviestarplanet.bonster.valueobjects.ActorBonsterAnimRel;
   import com.moviestarplanet.bonster.valueobjects.ActorBonsterRelItem;
   import com.moviestarplanet.bonster.valueobjects.BonsterAnim;
   import com.moviestarplanet.bonster.valueobjects.BonsterAnimationList;
   import com.moviestarplanet.bonster.valueobjects.BonsterCandyPriceWithLevel;
   import com.moviestarplanet.bonster.valueobjects.BonsterInteractionResponse;
   import com.moviestarplanet.bonster.valueobjects.BonsterObject;
   import com.moviestarplanet.bonster.valueobjects.BonsterTemplateObject;
   import com.moviestarplanet.chatCommunicator.chatHelpers.chatpermission.ChatPermissionInfo;
   import com.moviestarplanet.chatrooms.model.NotificationChatromObject;
   import com.moviestarplanet.clientcensor.AlertWordCounter;
   import com.moviestarplanet.commonvalueobjects.activity.PagedTodoList;
   import com.moviestarplanet.commonvalueobjects.actor.BlockedAndBlockingActorsResult;
   import com.moviestarplanet.commonvalueobjects.actor.Mood;
   import com.moviestarplanet.commonvalueobjects.actor.MoodWithVersion;
   import com.moviestarplanet.commonvalueobjects.login.FeatureValueObject;
   import com.moviestarplanet.commonvalueobjects.login.PostLoginData;
   import com.moviestarplanet.contentservices.valueobjects.VideoListExtendedData;
   import com.moviestarplanet.design.service.DesignRegistrator;
   import com.moviestarplanet.entities.valueobjects.ActorEntityCommentList;
   import com.moviestarplanet.entities.valueobjects.EntityCommentList;
   import com.moviestarplanet.forum.valueobjects.ForumAuthor;
   import com.moviestarplanet.forum.valueobjects.PagedPostList;
   import com.moviestarplanet.forum.valueobjects.PagedTopicList;
   import com.moviestarplanet.forum.valueobjects.Post;
   import com.moviestarplanet.forum.valueobjects.Topic;
   import com.moviestarplanet.friendship.FriendshipRegistrator;
   import com.moviestarplanet.look.valueobjects.Look;
   import com.moviestarplanet.look.valueobjects.LookItem;
   import com.moviestarplanet.look.valueobjects.PagedLookList;
   import com.moviestarplanet.media.valueobjects.ActorAnimationRel;
   import com.moviestarplanet.media.valueobjects.ActorBackgroundRel;
   import com.moviestarplanet.media.valueobjects.ActorMusicRel;
   import com.moviestarplanet.media.valueobjects.Animation;
   import com.moviestarplanet.media.valueobjects.AnimationCategory;
   import com.moviestarplanet.media.valueobjects.Background;
   import com.moviestarplanet.media.valueobjects.BackgroundCategory;
   import com.moviestarplanet.media.valueobjects.GiftPurchaseType;
   import com.moviestarplanet.media.valueobjects.HighscoreAnimation;
   import com.moviestarplanet.media.valueobjects.Music;
   import com.moviestarplanet.media.valueobjects.MusicCategory;
   import com.moviestarplanet.media.valueobjects.VipCertificate;
   import com.moviestarplanet.movies.MovieRegistrator;
   import com.moviestarplanet.moviestar.utils.AppearanceData;
   import com.moviestarplanet.moviestar.valueObjects.Actor;
   import com.moviestarplanet.moviestar.valueObjects.ActorClothesRel;
   import com.moviestarplanet.moviestar.valueObjects.ActorClothesRel2;
   import com.moviestarplanet.moviestar.valueObjects.ActorMinimal;
   import com.moviestarplanet.moviestar.valueObjects.Cloth;
   import com.moviestarplanet.moviestar.valueObjects.ClothesCategory;
   import com.moviestarplanet.moviestar.valueObjects.Design;
   import com.moviestarplanet.moviestar.valueObjects.Eye;
   import com.moviestarplanet.moviestar.valueObjects.EyeShadow;
   import com.moviestarplanet.moviestar.valueObjects.Mouth;
   import com.moviestarplanet.moviestar.valueObjects.Nose;
   import com.moviestarplanet.moviestar.valueObjects.RegisterNewUserData;
   import com.moviestarplanet.moviestar.valueObjects.SlotType;
   import com.moviestarplanet.news.module.NewsRegistrator;
   import com.moviestarplanet.notifications.model.NotificationAppearanceObject;
   import com.moviestarplanet.notifications.model.NotificationAutographObject;
   import com.moviestarplanet.notifications.model.NotificationChatObject;
   import com.moviestarplanet.notifications.model.NotificationEntityObject;
   import com.moviestarplanet.notifications.model.NotificationHugObject;
   import com.moviestarplanet.notifications.model.NotificationLegacyObject;
   import com.moviestarplanet.notifications.model.NotificationObject;
   import com.moviestarplanet.notifications.model.rbp.NotificationRbpXpGiftObject;
   import com.moviestarplanet.payment.valueobject.CountryPrices;
   import com.moviestarplanet.payment.valueobject.GetBokuBuyUrlResult;
   import com.moviestarplanet.payment.valueobject.KeyPrice;
   import com.moviestarplanet.payment.valueobject.PagedTransactionList;
   import com.moviestarplanet.payment.valueobject.PagedTransactionPurchaseTypeList;
   import com.moviestarplanet.payment.valueobject.PaymentMethodDescriptor;
   import com.moviestarplanet.payment.valueobject.PropertyPair;
   import com.moviestarplanet.payment.valueobject.PurchaseItemDomain;
   import com.moviestarplanet.payment.valueobject.PurchaseTypeDomain;
   import com.moviestarplanet.payment.valueobject.PurchaseVisualDomain;
   import com.moviestarplanet.payment.valueobject.RecurringPaymentSubscription;
   import com.moviestarplanet.payment.valueobject.Transaction;
   import com.moviestarplanet.payment.valueobject.TransactionPurchaseType;
   import com.moviestarplanet.payment.valueobject.VerifyBokuTransactionResult;
   import com.moviestarplanet.pet.valueobjects.ActorClickItemRel;
   import com.moviestarplanet.pet.valueobjects.ClickItemVO;
   import com.moviestarplanet.piggybank.service.PiggyBank;
   import com.moviestarplanet.quest.gifthunt.GiftHuntData;
   import com.moviestarplanet.quest.valueobjects.DynamicObjective;
   import com.moviestarplanet.quest.valueobjects.DynamicQuest;
   import com.moviestarplanet.quest.valueobjects.QuestStatus;
   import com.moviestarplanet.quest.valueobjects.SpecialQuestInitialUpdate;
   import com.moviestarplanet.quest.valueobjects.SpecialQuestProgressUpdate;
   import com.moviestarplanet.quest.valueobjects.SpecialQuestReward;
   import com.moviestarplanet.quest.valueobjects.StaticHint;
   import com.moviestarplanet.quest.valueobjects.StaticObjective;
   import com.moviestarplanet.quest.valueobjects.StaticQuest;
   import com.moviestarplanet.schoolfriends.valueobjects.ActorSchoolInformation;
   import com.moviestarplanet.schoolfriends.valueobjects.SchoolValueObject;
   import com.moviestarplanet.scrapblog.valueobjects.PagedScrapBlogList;
   import com.moviestarplanet.scrapblog.valueobjects.ScrapBlog;
   import com.moviestarplanet.scrapblog.valueobjects.ScrapBlogActorNameValueObject;
   import com.moviestarplanet.scrapblog.valueobjects.ScrapBlogListItem;
   import com.moviestarplanet.scrapitems.valueobjects.ClipArt;
   import com.moviestarplanet.scrapitems.valueobjects.ClipArtCategory;
   import com.moviestarplanet.scrapitems.valueobjects.ClipArtType;
   import com.moviestarplanet.services.actorservice.valueObjects.ActorRoom;
   import com.moviestarplanet.services.actorservice.valueObjects.ActorRoomInfo;
   import com.moviestarplanet.services.actorservice.valueObjects.RoomBoyFriend;
   import com.moviestarplanet.services.gifts.GiftService;
   import com.moviestarplanet.services.mobileservices.AMFLoginResult;
   import com.moviestarplanet.services.pollservice.valueObject.PollActorInfo;
   import com.moviestarplanet.services.pollservice.valueObject.PollData;
   import com.moviestarplanet.services.pollservice.valueObject.PollResult;
   import com.moviestarplanet.services.spendingservice.valueObjects.FameWheelResponse;
   import com.moviestarplanet.services.spendingservice.valueObjects.SpecialsGreetingItemInfo;
   import com.moviestarplanet.services.upload.UploadRegistrator;
   import com.moviestarplanet.services.videoservice.valueObjects.ExternalVideoData;
   import com.moviestarplanet.services.videoservice.valueObjects.ExternalVideoPlaylistRelData;
   import com.moviestarplanet.services.videoservice.valueObjects.ExternalVideoReturnData;
   import com.moviestarplanet.services.videoservice.valueObjects.ExternalVideoSimpleData;
   import com.moviestarplanet.services.videoservice.valueObjects.PagedExternalVideosData;
   import com.moviestarplanet.services.videoservice.valueObjects.PlaylistInfoData;
   import com.moviestarplanet.services.videoservice.valueObjects.PlaylistListData;
   import com.moviestarplanet.services.videoservice.valueObjects.VideoListData;
   import com.moviestarplanet.services.videoservice.valueObjects.YTActorLikeData;
   import com.moviestarplanet.services.videoservice.valueObjects.YTPlaylistData;
   import com.moviestarplanet.services.worldthemeservice.WorldAreaSwf;
   import com.moviestarplanet.services.worldthemeservice.WorldTheme;
   import com.moviestarplanet.services.worldthemeservice.WorldThemeChatRoom;
   import com.moviestarplanet.services.worldthemeservice.WorldThemeChatRoomInfo;
   import com.moviestarplanet.services.worldthemeservice.WorldThemeInfo;
   import com.moviestarplanet.session.valueobjects.AppSetting;
   import com.moviestarplanet.usersession.UserSessionRegistrator;
   import com.moviestarplanet.usersession.valueobjects.ActorEmail;
   import com.moviestarplanet.valueObjects.FriendListItem;
   import com.moviestarplanet.valueObjects.InitialLoginFriend;
   import com.moviestarplanet.valueObjects.MySpecialFriend;
   import com.moviestarplanet.valueObjects.PagedEntityCommentList;
   import com.moviestarplanet.valueObjects.PagedMobileFriendList;
   import com.moviestarplanet.valueObjects.PagedWallPostList;
   import com.moviestarplanet.valueObjects.ProfileSummary;
   import com.moviestarplanet.valueObjects.SearchableFriendItem;
   import com.moviestarplanet.valueObjects.WallPostItem;
   import com.moviestarplanet.valueObjectsCustom.AdControlData;
   import com.moviestarplanet.valueObjectsCustom.AddUserGamePointsResults;
   import com.moviestarplanet.valueObjectsCustom.BuyClothesResponse;
   import com.moviestarplanet.valueObjectsCustom.MessagingActor;
   import com.moviestarplanet.valueObjectsCustom.RequestAwardDataParameter;
   import com.moviestarplanet.valueObjectsCustom.StartupAwardRequestResult;
   import com.moviestarplanet.valueObjectsCustom.UserGamePointsParameter;
   import com.moviestarplanet.valueObjectsCustom.UserGameStatusDataResult;
   import flash.net.registerClassAlias;
   import mx.collections.ArrayCollection;
   import mx.messaging.config.ConfigMap;
   import mx.messaging.messages.AcknowledgeMessage;
   import mx.messaging.messages.AcknowledgeMessageExt;
   import mx.messaging.messages.CommandMessage;
   import mx.messaging.messages.CommandMessageExt;
   import mx.messaging.messages.ErrorMessage;
   import mx.messaging.messages.MessagePerformanceInfo;
   import mx.messaging.messages.RemotingMessage;
   import mx.utils.ObjectProxy;
   
   public class RegisterClassCommand
   {
      
      public function RegisterClassCommand()
      {
         super();
      }
      
      public function execute() : void
      {
         new ClubRegistrator().registerClassAliases();
         new MovieRegistrator().registerClassAliases();
         new NewsRegistrator().registerClassAliases();
         new UserSessionRegistrator().registerClassAliases();
         new DesignRegistrator().registerClassAliases();
         new AdminRegistrator().registerClassAliases();
         new FriendshipRegistrator().registerClassAliases();
         new UploadRegistrator().registerClassAliases();
         new AdminRegistrator().registerClassAliases();
         new SpecialCharactersRegistrator().registerClassAliases();
         new GiftService().registerClassAliases();
         registerClassAlias("flex.messaging.io.ArrayCollection",ArrayCollection);
         registerClassAlias("flex.messaging.io.ObjectProxy",ObjectProxy);
         registerClassAlias("flex.messaging.config.ConfigMap",ConfigMap);
         registerClassAlias("flex.messaging.messages.ErrorMessage",ErrorMessage);
         registerClassAlias("flex.messaging.messages.CommandMessage",CommandMessage);
         registerClassAlias("flex.messaging.messages.RemotingMessage",RemotingMessage);
         registerClassAlias("flex.messaging.messages.AcknowledgeMessage",AcknowledgeMessage);
         registerClassAlias("flex.messaging.messages.MessagePerformanceInfo",MessagePerformanceInfo);
         registerClassAlias("DSA",AcknowledgeMessageExt);
         registerClassAlias("DSC",CommandMessageExt);
         registerClassAlias("MovieStarPlanet.DBML.ActorEmail",ActorEmail);
         registerClassAlias("MovieStarPlanet.DBML.ActorAnimationRel",ActorAnimationRel);
         registerClassAlias("MovieStarPlanet.DBML.ActorBackgroundRel",ActorBackgroundRel);
         registerClassAlias("MovieStarPlanet.Model.AMFModels.Gifts.AMFGiftableMembership",VipCertificate);
         registerClassAlias("MovieStarPlanet.Model.AMFModels.Gifts.AMFGiftPurchaseType",GiftPurchaseType);
         registerClassAlias("MovieStarPlanet.DBML.ActorClickItemRel",ActorClickItemRel);
         registerClassAlias("MovieStarPlanet.DBML.ActorMusicRel",ActorMusicRel);
         registerClassAlias("MovieStarPlanet.DBML.Animation",Animation);
         registerClassAlias("MovieStarPlanet.DBML.AnimationCategory",AnimationCategory);
         registerClassAlias("MovieStarPlanet.DBML.Background",Background);
         registerClassAlias("MovieStarPlanet.DBML.BackgroundCategory",BackgroundCategory);
         registerClassAlias("MovieStarPlanet.DBML.ClickItem",ClickItemVO);
         registerClassAlias("MovieStarPlanet.DBML.HighscoreAnimation",HighscoreAnimation);
         registerClassAlias("MovieStarPlanet.DBML.Music",Music);
         registerClassAlias("MovieStarPlanet.DBML.MusicCategory",MusicCategory);
         registerClassAlias("MovieStarPlanet.WebService.ActorService.MoodWithVersion",MoodWithVersion);
         registerClassAlias("MovieStarPlanet.DBML.Mood",Mood);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.UiActor",Actor);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.Mouth",Mouth);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.Nose",Nose);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.Eye",Eye);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.EyeShadow",EyeShadow);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.UiActorClothes",Cloth);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.UiActorClothesRel",ActorClothesRel);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.UiActorClothesCategory",ClothesCategory);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.UiActorClothesSlotType",SlotType);
         registerClassAlias("MovieStarPlanet.Model.Actor.ValueObjects.UiActorClothesDesign",Design);
         registerClassAlias("MovieStarPlanet.DBML.Actor",Actor);
         registerClassAlias("MovieStarPlanet.DBML.Mouth",Mouth);
         registerClassAlias("MovieStarPlanet.DBML.Nose",Nose);
         registerClassAlias("MovieStarPlanet.DBML.Eye",Eye);
         registerClassAlias("MovieStarPlanet.DBML.EyeShadow",EyeShadow);
         registerClassAlias("MovieStarPlanet.DBML.ActorClothesRel",ActorClothesRel);
         registerClassAlias("MovieStarPlanet.DBML.Cloth",Cloth);
         registerClassAlias("MovieStarPlanet.DBML.ClothesCategory",ClothesCategory);
         registerClassAlias("MovieStarPlanet.DBML.Design",Design);
         registerClassAlias("MovieStarPlanet.DBML.Todo",Todo);
         registerClassAlias("MovieStarPlanet.DBML.TodoActor",TodoActor);
         registerClassAlias("MovieStarPlanet.DBML.TodoContest",TodoContest);
         registerClassAlias("MovieStarPlanet.DBML.TodoMovie",TodoMovie);
         registerClassAlias("MovieStarPlanet.DBML.TodoMovieCompetition",TodoMovieCompetition);
         registerClassAlias("MovieStarPlanet.WebService.MovieStar.MovieStarService+RegisterNewUserData",RegisterNewUserData);
         registerClassAlias("MovieStarPlanet.WebService.AMFActorService+AMFLoginResult",AMFLoginResult);
         registerClassAlias("MovieStarPlanet.WebService.BaseWebService+TicketHeader",TicketHeader);
         registerClassAlias("MovieStarPlanet.WebService.WebService+FriendListItem",FriendListItem);
         registerClassAlias("MovieStarPlanet.WebService.WebService+InitialLoginFriend",InitialLoginFriend);
         registerClassAlias("MovieStarPlanet.WebService.WebService+SearchableFriendItem",SearchableFriendItem);
         registerClassAlias("MovieStarPlanet.WebService.WebService+PagedMobileFriendList",PagedMobileFriendList);
         registerClassAlias("MovieStarPlanet.WebService.Looks.AMFLookService+PagedLookList",PagedLookList);
         registerClassAlias("MovieStarPlanet.DBML.LookItem",LookItem);
         registerClassAlias("MovieStarPlanet.DBML.Look",Look);
         registerClassAlias("MovieStarPlanet.DBML.WallPostLink",WallPostLink);
         registerClassAlias("MovieStarPlanet.Model.Activity.ValueObjects.PagedActivityList",PagedActivityList);
         registerClassAlias("MovieStarPlanet.Model.Activity.Activity",Activity);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityActor",ActivityActor);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityContest",ActivityContest);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityLook",ActivityLook);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityMovie",ActivityMovie);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityMood",ActivityMood);
         registerClassAlias("MovieStarPlanet.Model.Activity.WallPostLink",WallPostLink);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityImageUpload",ActivityImageUpload);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityScrapBlog",ActivityScrapBlog);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityWallPost",ActivityWallPost);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityUpdater",ActivityUpdater);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityExternalVideo",ActivityExternalVideo);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityExternalVideoActorRel",ActivityExternalVideoActorRel);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityExternalVideoPlaylistRel",ActivityExternalVideoPlaylistRel);
         registerClassAlias("MovieStarPlanet.Model.Activity.ActivityDesign",ActivityDesign);
         registerClassAlias("MovieStarPlanet.WebService.ServiceResult",AmfServiceResultData);
         registerClassAlias("MovieStarPlanet.WebService.AmfServiceResultData",AmfServiceResultData);
         registerClassAlias("MovieStarPlanet.WebService.WebService+UserGameStatusDataResult",UserGameStatusDataResult);
         registerClassAlias("MovieStarPlanet.WebService.WebService+AddUserGamePointsResult",AddUserGamePointsResults);
         registerClassAlias("MovieStarPlanet.WebService.WebService+UserGamePointsParameter",UserGamePointsParameter);
         registerClassAlias("MovieStarPlanet.WebService.WebService+RequestAwardDataParameter",RequestAwardDataParameter);
         registerClassAlias("MovieStarPlanet.WebService.WorldTheme+WorldAreaSwf",WorldAreaSwf);
         registerClassAlias("MovieStarPlanet.WebService.WorldTheme+WorldTheme",WorldTheme);
         registerClassAlias("MovieStarPlanet.WebService.WorldTheme+WorldThemeInfo",WorldThemeInfo);
         registerClassAlias("MovieStarPlanet.WebService.WorldTheme+WorldThemeChatRoomInfo",WorldThemeChatRoomInfo);
         registerClassAlias("MovieStarPlanet.WebService.WorldTheme+WorldThemeChatRoom",WorldThemeChatRoom);
         registerClassAlias("MovieStarPlanet.WebService.State.PostLogin.PostLoginData",PostLoginData);
         registerClassAlias("MovieStarPlanet.Model.Features.ValueObjects.FeatureVO",FeatureValueObject);
         registerClassAlias("MovieStarPlanet.WebService.ActorService.GiftHunt",GiftHuntData);
         registerClassAlias("MovieStarPlanet.DBML.Post",Post);
         registerClassAlias("MovieStarPlanet.DBML.ForumAuthor",ForumAuthor);
         registerClassAlias("MovieStarPlanet.WebService.Forums.AMFForumService+TopicResult",Topic);
         registerClassAlias("MovieStarPlanet.WebService.Forums.AMFForumService+PagedPostList",PagedPostList);
         registerClassAlias("MovieStarPlanet.WebService.Forums.AMFForumService+PagedTopicResultList",PagedTopicList);
         registerClassAlias("MovieStarPlanet.Polls.PollResult",PollResult);
         registerClassAlias("MovieStarPlanet.Polls.PollData",PollData);
         registerClassAlias("MovieStarPlanet.Polls.PollActorInfo",PollActorInfo);
         registerClassAlias("MovieStarPlanet.WebService.WebService+BlockedAndBlockingActorsResult",BlockedAndBlockingActorsResult);
         registerClassAlias("MovieStarPlanet.WebService.WebService+StartupAwardRequestResult",StartupAwardRequestResult);
         registerClassAlias("MovieStarPlanet.WebService.Video.ExternalVideoSimple",ExternalVideoSimpleData);
         registerClassAlias("MovieStarPlanet.WebService.Video.PlaylistInfo",PlaylistInfoData);
         registerClassAlias("MovieStarPlanet.WebService.Video.ExternalVideo",ExternalVideoData);
         registerClassAlias("MovieStarPlanet.WebService.Video.ExternalVideoPlaylistRel",ExternalVideoPlaylistRelData);
         registerClassAlias("MovieStarPlanet.WebService.Video.YTActorLike",YTActorLikeData);
         registerClassAlias("MovieStarPlanet.WebService.Video.ExternalVideoReturnObject",ExternalVideoReturnData);
         registerClassAlias("MovieStarPlanet.WebService.Video.PlaylistListObject",PlaylistListData);
         registerClassAlias("MovieStarPlanet.WebService.Video.YTPlaylist",YTPlaylistData);
         registerClassAlias("MovieStarPlanet.WebService.Video.VideoListObject",VideoListData);
         registerClassAlias("MovieStarPlanet.WebService.Video.VideoListObjectExtended",VideoListExtendedData);
         registerClassAlias("MovieStarPlanet.WebService.Video.PagedExternalVideos",PagedExternalVideosData);
         registerClassAlias("MovieStarPlanet.DBML.ActorClickItemRel",ActorClickItemRel);
         registerClassAlias("MovieStarPlanet.DBML.ClickItem",ClickItemVO);
         registerClassAlias("MovieStarPlanet.WebService.Postlogin.AdControl.AdControlData",AdControlData);
         registerClassAlias("MovieStarPlanet.WebService.Friendships.MySpecialFriend",MySpecialFriend);
         registerClassAlias("MovieStarPlanet.WebService.Friendships.PagedTodoList",PagedTodoList);
         registerClassAlias("MovieStarPlanet.WebService.WebService+AlertWordCounter",AlertWordCounter);
         registerClassAlias("MovieStarPlanet.WebService.Profile.ProfileService+ProfileSummary",ProfileSummary);
         registerClassAlias("MovieStarPlanet.WebService.PurchaseItemDomain",PurchaseItemDomain);
         registerClassAlias("MovieStarPlanet.WebService.PurchaseVisualDomain",PurchaseVisualDomain);
         registerClassAlias("MovieStarPlanet.WebService.PurchaseTypeDomain",PurchaseTypeDomain);
         registerClassAlias("MovieStarPlanet.WebService.WebService+VerifyBokuTransactionResult",VerifyBokuTransactionResult);
         registerClassAlias("MovieStarPlanet.WebService.WebService+GetBokuBuyUrlResult",GetBokuBuyUrlResult);
         registerClassAlias("MovieStarPlanet.WebService.WebService+PropertyPair",PropertyPair);
         registerClassAlias("MovieStarPlanet.WebService.WebService+PaymentMethodDescriptor",PaymentMethodDescriptor);
         registerClassAlias("MovieStarPlanet.WebService.WebService+TransactionPurchaseType",TransactionPurchaseType);
         registerClassAlias("MovieStarPlanet.WebService.WebService+PagedTransactionPurchaseTypeList",PagedTransactionPurchaseTypeList);
         registerClassAlias("MovieStarPlanet.WebService.WebService+PagedTransactionList",PagedTransactionList);
         registerClassAlias("MovieStarPlanet.WebService.WebService+RecurringPaymentSubscription",RecurringPaymentSubscription);
         registerClassAlias("MovieStarPlanet.WebService.WebService+CountryPrices",CountryPrices);
         registerClassAlias("MovieStarPlanet.WebService.WebService+KeyPrice",KeyPrice);
         registerClassAlias("MovieStarPlanet.DBML.Transaction",Transaction);
         registerClassAlias("com.moviestarplanet.amf.PagerResultObject",PagerResultObject);
         registerClassAlias("MovieStarPlanet.WebService.User.UserService+AppSetting",AppSetting);
         registerClassAlias("MovieStarPlanet.WebService.Profile.WallPostItem",WallPostItem);
         registerClassAlias("MovieStarPlanet.WebService.WebService+ActorRoomInfo",ActorRoomInfo);
         registerClassAlias("MovieStarPlanet.DBML.ActorRoom",ActorRoom);
         registerClassAlias("MovieStarPlanet.DBML.RoomBoyFriend",RoomBoyFriend);
         registerClassAlias("MovieStarPlanet.WebService.Profile.ProfileService+PagedWallPostList",PagedWallPostList);
         registerClassAlias("MovieStarPlanet.WebService.Session.ChatPermissionInfo",ChatPermissionInfo);
         registerClassAlias("MovieStarPlanet.DBML.SpecialsGreetingItemInfo",SpecialsGreetingItemInfo);
         registerClassAlias("MovieStarPlanet.DBML.ActorClothesRel",ActorClothesRel);
         registerClassAlias("MovieStarPlanet.DBML.ActorClothesRel2",ActorClothesRel2);
         registerClassAlias("MovieStarPlanet.WebService.WebService+BuyClothesResponse",BuyClothesResponse);
         registerClassAlias("MovieStarPlanet.WebService.ServiceResultData`1[[MovieStarPlanet.WebService.Spending.FameWheelResponse, MSPWebservice, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",ServiceResultData);
         registerClassAlias("MovieStarPlanet.WebService.Spending.FameWheelResponse",FameWheelResponse);
         registerClassAlias("MovieStarPlanet.DBML.EntityCommentList",EntityCommentList);
         registerClassAlias("MovieStarPlanet.DBML.ActorEntityCommentList",ActorEntityCommentList);
         registerClassAlias("MovieStarPlanet.WebService.Bonster.ActorBonsterRelItem",ActorBonsterRelItem);
         registerClassAlias("MovieStarPlanet.WebService.Bonster.BonsterCandyPriceWithLevel",BonsterCandyPriceWithLevel);
         registerClassAlias("MovieStarPlanet.DBML.Bonster",BonsterObject);
         registerClassAlias("MovieStarPlanet.DBML.BonsterTemplate",BonsterTemplateObject);
         registerClassAlias("MovieStarPlanet.DBML.BonsterAnimation",BonsterAnim);
         registerClassAlias("MovieStarPlanet.DBML.ActorBonsterAnimRel",ActorBonsterAnimRel);
         registerClassAlias("MovieStarPlanet.WebService.Bonster.AnimationList",BonsterAnimationList);
         registerClassAlias("MovieStarPlanet.WebService.Bonster.BonsterInteractionResponse",BonsterInteractionResponse);
         registerClassAlias("ClipArt",ClipArt);
         registerClassAlias("MovieStarPlanet.WebService.ScrapBlog.ClipArt",ClipArt);
         registerClassAlias("MovieStarPlanet.WebService.ScrapBlog.ClipArtType",ClipArtType);
         registerClassAlias("MovieStarPlanet.WebService.ScrapBlog.ClipArtCategory",ClipArtCategory);
         registerClassAlias("MovieStarPlanet.WebService.WebService+PagedEntityCommentList",PagedEntityCommentList);
         registerClassAlias("MovieStarPlanet.WebService.ScrapBlog.AMFScrapBlogService+PagedScrapBlogList",PagedScrapBlogList);
         registerClassAlias("MovieStarPlanet.WebService.ScrapBlog.ScrapBlogListItem",ScrapBlogListItem);
         registerClassAlias("MovieStarPlanet.WebService.ScrapBlog.ScrapBlog",ScrapBlog);
         registerClassAlias("MovieStarPlanet.WebService.ScrapBlog.ScrapBlogActorName",ScrapBlogActorNameValueObject);
         registerClassAlias("MovieStarPlanet.DBML.School",SchoolValueObject);
         registerClassAlias("MovieStarPlanet.Model.School.ValueObjects.ActorSchoolInformation",ActorSchoolInformation);
         registerClassAlias("MovieStarPlanet.Model.PiggyBank.ValueObjects.PiggyBankVO",PiggyBank);
         registerClassAlias("NotificationObject",NotificationObject);
         registerClassAlias("NotificationEntityObject",NotificationEntityObject);
         registerClassAlias("NotificationLegacyObject",NotificationLegacyObject);
         registerClassAlias("NotificationChatromObject",NotificationChatromObject);
         registerClassAlias("NotificationAppearanceObject",NotificationAppearanceObject);
         registerClassAlias("NotificationChatObject",NotificationChatObject);
         registerClassAlias("NotificationAutographObject",NotificationAutographObject);
         registerClassAlias("NotificationHugObject",NotificationHugObject);
         registerClassAlias("NotificationRbpXpGiftObject",NotificationRbpXpGiftObject);
         registerClassAlias("MovieStarPlanet.WebService.Messaging.MessagingActor",MessagingActor);
         registerClassAlias("MovieStarPlanet.Model.Activity.ValueObjects.AutographResponseVO",AutographResponseVO);
         registerClassAlias("MovieStarPlanet.WebService.Quest.SpecialQuestInitialUpdate",SpecialQuestInitialUpdate);
         registerClassAlias("MovieStarPlanet.WebService.Quest.SpecialQuestReward",SpecialQuestReward);
         registerClassAlias("MovieStarPlanet.WebService.Quest.QuestStatus",QuestStatus);
         registerClassAlias("MovieStarPlanet.WebService.Quest.StaticQuest",StaticQuest);
         registerClassAlias("MovieStarPlanet.WebService.Quest.StaticObjective",StaticObjective);
         registerClassAlias("MovieStarPlanet.WebService.Quest.StaticHint",StaticHint);
         registerClassAlias("MovieStarPlanet.WebService.Quest.DynamicQuest",DynamicQuest);
         registerClassAlias("MovieStarPlanet.WebService.Quest.DynamicObjective",DynamicObjective);
         registerClassAlias("MovieStarPlanet.WebService.Quest.SpecialQuestProgressUpdate",SpecialQuestProgressUpdate);
         registerClassAlias("ActorMinimal",ActorMinimal);
         registerClassAlias("AppearanceData",AppearanceData);
      }
   }
}

